tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: content
            field:
              type: markdown
              localizable: true
          -
            handle: allergenen
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                new_set_group:
                  display: 'New Set Group'
                  instructions: null
                  icon: null
                  sets:
                    new_set:
                      display: 'New Set'
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: allergeen
                          field:
                            input_type: text
                            antlers: false
                            type: text
                            display: Allergeen
                            icon: text
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            replicator_preview: true
                            hide_display: false
              type: replicator
              display: Allergenen
              icon: replicator
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: rating
            field:
              type: text
              display: Rating
              width: 50
              instructions: 'The rating of this entry'
              validate: required|numeric
              read_only: true
              default: 0
          -
            handle: rates
            field:
              type: grid
              display: Rates
              instructions: 'The rates of this entry'
              fields:
                -
                  handle: rate
                  field:
                    type: text
                    display: Rate
                    width: 50
                    instructions: 'The rate of this entry'
                    validate: required|numeric
                -
                  handle: comment
                  field:
                    type: text
                    display: Comment
                    width: 50
                    instructions: 'The comment of this entry'
                    validate: required
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
          -
            handle: parent
            field:
              type: entries
              collections:
                - products
              max_items: 1
              listable: false
              localizable: true
          -
            handle: types
            field:
              type: terms
              taxonomies:
                - types
              display: Types
              mode: select
title: Product
